---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:16.1.4
  amd64: ghcr.io/hassio-addons/base-python/amd64:16.1.4
  armhf: ghcr.io/hassio-addons/base-python/armhf:16.1.4
  armv7: ghcr.io/hassio-addons/base-python/armv7:16.1.4
  i386: ghcr.io/hassio-addons/base-python/i386:16.1.4
