---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:15.0.1
  amd64: ghcr.io/hassio-addons/base-python/amd64:15.0.1
  armhf: ghcr.io/hassio-addons/base-python/armhf:15.0.1
  armv7: ghcr.io/hassio-addons/base-python/armv7:15.0.1
  i386: ghcr.io/hassio-addons/base-python/i386:15.0.1
