---
build_from:
  aarch64: ghcr.io/hassio-addons/base-python/aarch64:17.0.0
  amd64: ghcr.io/hassio-addons/base-python/amd64:17.0.0
  armhf: ghcr.io/hassio-addons/base-python/armhf:17.0.0
  armv7: ghcr.io/hassio-addons/base-python/armv7:17.0.0
  i386: ghcr.io/hassio-addons/base-python/i386:17.0.0
